'use strict';
(function(){
 const catalog=window.ESCAPE_ARCHIVE, projects=catalog.projects, $=s=>document.querySelector(s),view=document.body.dataset.view;
 const esc=v=>String(v??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
 const statusName={preview:'미리보기',released:'플레이 가능',draft:'제작 중'};
 function localPath(value){return typeof value==='string'&&/^\.\/[a-zA-Z0-9_./-]+$/.test(value)&&!value.includes('..')?value:null}
 const projectUrl=p=>'./project.html?id='+encodeURIComponent(p.id),playUrl=p=>'./play.html?id='+encodeURIComponent(p.id);
 function art(p,extra=''){const src=localPath(p.cover);return src?`<div class="artwork ${p.coverMode==='triptych-right'?'triptych-right':''} ${extra}"><img src="${esc(src)}" alt="${esc(p.coverAlt)}" width="${p.coverMode==='triptych-right'?2172:1672}" height="${p.coverMode==='triptych-right'?724:941}" ${extra==='detail-art'?'fetchpriority="high"':'loading="lazy"'}></div>`:'<div class="artwork artwork-empty" aria-label="표지 준비 중"><span>ESCAPE ARCHIVE</span></div>'}
 function canPlay(p){return p.status!=='draft'&&Boolean(localPath(p.playPath))}
 function playLink(p,label='플레이하기'){return canPlay(p)?`<a class="button-primary" href="${playUrl(p)}">${label} <span aria-hidden="true">↗</span></a>`:'<span class="unavailable">다음 이야기를 준비하고 있어요.</span>'}
 function card(p){return `<article class="project-card"><a class="cover-link" href="${projectUrl(p)}" aria-label="${esc(p.title)} 작품 소개">${art(p)}<div class="cover-top"><span class="case-number">FILE / ${esc(p.number)}</span><span class="status-label">${statusName[p.status]||'미리보기'} · v${esc(p.version)}</span></div><span class="cover-arrow" aria-hidden="true">↗</span></a><div class="card-meta"><span>${esc(p.genre)}</span><span>${esc(p.players)} · ${esc(p.duration)}</span></div><h3><a href="${projectUrl(p)}">${esc(p.title)}</a></h3><p class="card-premise">${esc(p.premise)}</p><div class="card-tags">${p.tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div><div class="card-actions">${playLink(p)}<a class="button-secondary" href="${projectUrl(p)}">작품 소개</a></div></article>`}
 function renderHome(){function filter(category){const items=projects.filter(p=>category==='all'||p.category===category);$('#projectGrid').innerHTML=items.length?items.map(card).join(''):'<div class="empty-state"><h3>아직 등록된 작품이 없어요.</h3><p>다른 장르의 이야기를 먼저 살펴보세요.</p><button class="button-secondary" id="resetFilter">전체 작품 보기</button></div>';$('#workCount').textContent=String(items.length).padStart(2,'0');$('#filterStatus').textContent=`${items.length}개의 작품을 표시합니다.`;document.querySelectorAll('[data-filter]').forEach(b=>{const selected=b.dataset.filter===category;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',String(selected))});if($('#resetFilter'))$('#resetFilter').onclick=()=>filter('all')};document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>filter(b.dataset.filter));filter('all');$('.edition').textContent=`COLLECTION / ${String(projects.length).padStart(2,'0')} WORKS`;}
 function notFound(container){container.innerHTML='<section class="empty-state"><span class="eyebrow">ARCHIVE / NOT FOUND</span><h1>이 기록을 찾지 못했어요.</h1><p>작품 주소가 바뀌었거나 아직 등록되지 않았습니다.</p><a class="button-primary" href="./index.html#works">작품 목록으로</a></section>';document.title='작품을 찾을 수 없습니다 — Escape Archive'}
 function renderProject(p){document.title=p.title+' — Escape Archive';$('meta[name="description"]').content=p.premise;const download=localPath(p.download);const related=projects.find(x=>x.id!==p.id);$('#projectContent').innerHTML=`<div class="detail-eyebrow"><span class="eyebrow">FILE ${esc(p.number)} / ${esc(p.genre)}</span><span class="status-label">${statusName[p.status]||'미리보기'} · v${esc(p.version)}</span></div><header class="detail-heading"><p>${esc(p.subtitle)}</p><h1>${esc(p.title)}</h1><div class="detail-quick"><span>${esc(p.players)} 플레이</span><span>약 ${esc(p.duration)}</span><span>PC · 모바일</span><span>한국어</span></div></header><div class="detail-cover">${art(p,'detail-art')}<blockquote>“${esc(p.hook)}”</blockquote></div><div class="detail-layout"><section class="story"><span class="eyebrow">THE STORY</span><h2>이야기의 시작</h2>${p.intro.map(x=>`<p>${esc(x)}</p>`).join('')}<div class="feature-list">${p.features.map((x,i)=>`<article><span class="feature-number">0${i+1}</span><div><h3>${esc(x.title)}</h3><p>${esc(x.text)}</p></div></article>`).join('')}</div></section><aside class="entry-card"><p class="eyebrow">ENTER THE STORY</p><h2>조사를 시작할까요?</h2><p>설치 없이 브라우저에서<br>바로 시작할 수 있습니다.</p>${playLink(p)}${download?`<a class="download-link" href="${esc(download)}" download>미리보기 파일 <span>ZIP · ${esc(p.downloadSize)} ↓</span></a>`:''}<dl><div><dt>제작</dt><dd>${esc(catalog.creator)}</dd></div><div><dt>최신 버전</dt><dd>v${esc(p.version)}</dd></div><div><dt>업데이트</dt><dd>${esc(p.updated.replaceAll('-','.'))}</dd></div></dl><details><summary>플레이 전에 확인해 주세요</summary><ul>${p.notes.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></details><details><summary>저장과 파일 실행 방법</summary><p>진행은 현재 브라우저에 저장됩니다. 게임의 설정 또는 일시정지 메뉴에서 진행 파일을 내려받으면 다른 기기에서도 이어갈 수 있습니다.</p><p>ZIP 파일은 압축을 푼 다음 dist 폴더의 index.html을 열어주세요.</p><p>이전에 내려받은 게임의 기록은 게임 안에서 진행 파일을 불러와 옮길 수 있습니다.</p></details></aside></div>${related?`<a class="next-work" href="${projectUrl(related)}"><span class="eyebrow">ANOTHER STORY</span><b>${esc(related.title)}</b><span aria-hidden="true">↗</span></a>`:''}`;}
 function renderPlayer(p){if(!canPlay(p)){notFound($('#playerContainer'));return}document.title=p.title+' 플레이 — Escape Archive';$('#playerTitle').textContent=p.title;$('#playerVersion').textContent='v'+p.version;const frame=document.createElement('iframe');frame.className='game-frame';frame.title=p.title+' 게임';frame.src=localPath(p.playPath);frame.allow='fullscreen';frame.setAttribute('allowfullscreen','');$('#playerContainer').replaceChildren(frame);$('#directPlay').href=localPath(p.playPath);$('#directPlay').classList.remove('hidden');if(document.fullscreenEnabled){$('#fullscreen').classList.remove('hidden');$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{const n=$('#notice');n.textContent='전체화면을 열 수 없습니다. 새 창으로 플레이할 수 있어요.';n.classList.add('visible');setTimeout(()=>n.classList.remove('visible'),4500)}};document.addEventListener('fullscreenchange',()=>{$('#fullscreen').textContent=document.fullscreenElement?'전체화면 닫기':'전체화면'})}}
 if(view==='home')renderHome();else{const id=new URLSearchParams(location.search).get('id'),p=projects.find(x=>x.id===id);if(!p)notFound(view==='play'?$('#playerContainer'):$('#projectContent'));else if(view==='project')renderProject(p);else if(view==='play')renderPlayer(p)}
})();
