'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], K=GameKit, E=Case0217, KEY='missing0217-v2';
let state=E.restore(K.read(KEY)), active=false, paused=false, lastTick=performance.now();
const mails={
 mail1:{clue:'date',title:'우리 여행 사진',meta:'언니 · 10월 16일 18:32',body:'서윤아, 첫 여행 때 찍은 사진 찾았어.<br><br>벌써 3년 전이라니. <mark>8월 23일</mark> 새벽 기차를 타겠다고 둘이 얼마나 들떠 있었는지 기억나? 네가 비밀번호를 자꾸 그 날짜로 해서 잊어버릴 일은 없겠다.<br><br>무슨 일 있는 건 아니지? 전화 좀 받아.'},
 mail2:{clue:'order',title:'사진 전달 순서',meta:'강민호 · 10월 15일 21:04',body:'전시용 사진 세 장 확인했어요.<br><br>파일명이 섞이지 않도록 <mark>A → B → C 순서</mark>로 보내주세요. 촬영 장소도 빠뜨리지 말고요. 장소를 이어 읽으면 이번 프로젝트 제목이 된다고 했죠?'},
 mail3:{clue:'time',title:'전송되지 않은 초안',meta:'보낸 편지함 · 10월 17일 02:16',body:'누군가 따라오고 있어.<br><br>전화는 위험해. 내가 남긴 기록을 찾았다면 오래된 역으로 와줘. 3번 출구 쪽이야. 시계가 멈춘 시간에 맞춰 보관함을 열어.<br><br><strong>02:17 자동 저장됨</strong>'}
};
const photos={A:{place:'서점 앞',time:'19:42',position:'0%',description:'문 닫은 서점 앞, 젖은 보도 위로 불빛이 번진다.'},B:{place:'림 카페',time:'20:08',position:'50%',description:'늦은 시간까지 불이 켜진 카페. 창가에는 아무도 없다.'},C:{place:'역 광장',time:'21:51',position:'100%',description:'어두워진 광장 너머, 오래된 역의 시계가 보인다.'}};
const clues={date:['첫 여행 날짜','언니의 메일: 첫 여행은 8월 23일.','inbox'],order:['전송 순서','민호의 메일: 사진은 A → B → C 순서.','inbox'],time:['마지막 연락','전송되지 않은 초안이 02:17에 자동 저장되었다.','inbox'],notes:['암호 규칙','PRIVATE 암호는 첫 여행 날짜. 월일부터 네 자리.','notes'],photoA:['사진 A','촬영 장소: 서점 앞 / 19:42','gallery'],photoB:['사진 B','촬영 장소: 림 카페 / 20:08','gallery'],photoC:['사진 C','촬영 장소: 역 광장 / 21:51','gallery'],record:['복구된 음성 기록','장소 첫 글자를 순서대로. 그 역의 3번 출구, 마지막 연락 시각.','vault']};
const hintSets={vault:['암호의 규칙과 실제 날짜가 서로 다른 앱에 있습니다. 메모부터 읽어보세요.','언니의 메일에 첫 여행 날짜가 있고, 메모는 월일부터 쓰라고 합니다.','8월 23일을 네 자리로 쓰면 0823입니다.'],record:['잠금이 풀린 PRIVATE에 복구된 기록이 있습니다.','REC_0217.m4a 옆의 기록 열기를 눌러보세요.','기록은 사진의 장소 첫 글자, 3번 출구, 마지막 연락 시각을 가리킵니다.'],photos:['사진의 모습보다 촬영 정보에 주목하세요.','사진 세 장을 각각 열어 장소를 단서 수첩에 모으세요.','A: 서점 앞, B: 림 카페, C: 역 광장입니다.'],route:['사진을 찍은 시간과 전송할 순서는 별개의 정보입니다.','민호의 메일은 A → B → C 순서로 보내라고 합니다.','A, B, C를 차례로 선택하면 장소 첫 글자는 서·림·역입니다.'],report:['역 이름만으로는 서윤을 찾기 어렵습니다. 출구 정보도 필요합니다.','복구 기록의 출구 번호와 초안의 마지막 저장 시각을 함께 확인하세요.','장소는 서림역 3번 출구, 보관함 암호는 0217입니다.']};
function save(){const ok=K.write(KEY,state);$('#saveStatus').textContent=ok?'자동 저장됨':'저장 불가 · 일시정지에서 진행 파일 보관';}
function timeText(n){n=Math.floor(n);return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`}
function mark(id){if(!state.clues.includes(id)){state.clues.push(id);K.toast('단서 수첩에 기록했습니다: '+clues[id][0]);}save();update();}
function update(){const count=state.clues.length;$('#progressText').textContent=`기록 ${count} / 8`;$('#progressBar').value=count;$('#objective').textContent=state.finished?'사건 해결 · 수집한 기록을 다시 볼 수 있습니다.':E.objective(state)[1];$('#timer').textContent=timeText(state.elapsed);$('#vaultState').textContent=state.vaultOpen?'복구 완료':'잠김';$('#vaultLocked').classList.toggle('hidden',state.vaultOpen);$('#vaultOpen').classList.toggle('hidden',!state.vaultOpen);$('#transcript').classList.toggle('hidden',!state.clues.includes('record'));$('#readRecord').textContent=state.clues.includes('record')?'다시 읽기':'기록 열기';$('#reportReadiness').textContent=E.objective(state)[0]==='report'?'필요한 단서가 모였습니다. 역 이름과 출구, 보관함 암호를 제출하세요.':'현재 목표를 마치면 조사 결과를 확정할 수 있습니다. 단서는 언제든 다시 볼 수 있습니다.';renderJournal();renderPhotos();}
function showMail(id){const m=mails[id];state.mail=id;$('#mailViewer').innerHTML=`<p class="mail-meta">${m.meta}</p><h3>${m.title}</h3><p>${m.body}</p>`;$$('[data-mail]').forEach(b=>{b.classList.toggle('selected',b.dataset.mail===id);b.setAttribute('aria-pressed',String(b.dataset.mail===id))});mark(m.clue)}
function showPanel(id,focus=true){if(!['inbox','gallery','notes','vault','report','journal'].includes(id))return;state.panel=id;$$('.panel').forEach(p=>p.classList.toggle('active-panel',p.id===id));$$('[data-panel]').forEach(b=>{b.classList.toggle('active',b.dataset.panel===id);if(b.dataset.panel===id)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});if(id==='inbox')showMail(state.mail);if(id==='notes')mark('notes');save();if(focus)$('#screen').focus({preventScroll:true});}
function renderJournal(){$('#journalCount').textContent=`${state.clues.length} / 8`;$('#journalList').innerHTML=state.clues.length?state.clues.map(id=>`<button class="journal-item" data-source="${id}"><span>${clues[id][0]}</span><p>${clues[id][1]}</p><small>원본 기록 열기</small></button>`).join(''):'<p class="empty">아직 수집한 기록이 없습니다. 메일부터 열어보세요.</p>';}
function renderPhotos(){$('#photoCount').textContent=`정보 ${['A','B','C'].filter(id=>state.clues.includes('photo'+id)).length} / 3 확인`;$('#photoGrid').innerHTML=['C','A','B'].map(id=>`<button class="photo-card" data-photo="${id}"><span class="photo-image photo-${id}" aria-hidden="true"></span><b>IMG_1016_${id}</b><small>${state.clues.includes('photo'+id)?photos[id].place+' · '+photos[id].time:'촬영 정보 열기'}</small></button>`).join('');$('#routeChoices').innerHTML=['C','A','B'].map(id=>`<button data-route="${id}" class="ghost ${state.photoOrder.includes(id)?'selected':''}" aria-pressed="${state.photoOrder.includes(id)}" ${!state.clues.includes('photo'+id)||state.routeSolved?'disabled':''}>${state.photoOrder.includes(id)?state.photoOrder.indexOf(id)+1+' · ':''}사진 ${id}</button>`).join('');$('#routeOrder').textContent=state.photoOrder.length?state.photoOrder.map(id=>photos[id].place).join(' → '):'아직 선택한 사진이 없습니다.';$('#checkRoute').disabled=state.routeSolved;if(state.routeSolved){$('#routeError').textContent='서 · 림 · 역 — 전송 목록이 복원되었습니다.';$('#checkRoute').textContent='배열 복원 완료';}else $('#checkRoute').textContent='장소 연결 확인';}
function start(){window.EscapeMusic?.start();$$('.feedback').forEach(el=>el.textContent='');state.started=true;active=true;paused=false;$('#briefing').classList.add('hidden');$('#ending').classList.add('hidden');$('#game').classList.remove('hidden');$('#investigatorNotes').value=state.notes;$('#placeAnswer').value=state.report.place;$('#timeAnswer').value=state.report.code;update();if(state.finished){finish(false);return}showPanel(state.panel,false);save();}
function finish(persist=true){if(persist){state.finished=true;save()}active=false;$('#game').classList.add('hidden');$('#ending').classList.remove('hidden');$('#resultTime').textContent=timeText(state.elapsed);$('#resultClues').textContent=state.clues.length+' / 8';$('#resultHints').textContent=state.hintUses+'회';$('#ending h1').tabIndex=-1;$('#ending h1').focus();}
function reset(){K.open('새 조사를 시작할까요?','<p>현재 조사 진행은 초기화됩니다. 필요한 경우 일시정지 메뉴에서 진행 파일을 먼저 보관하세요.</p><div class="dialog-actions"><button data-close-dialog class="ghost">돌아가기</button><button id="confirmReset" class="primary">처음부터 시작</button></div>');$('#confirmReset').onclick=()=>{state=E.fresh();save();K.close();start()};}
function hint(level){const key=E.objective(state)[0],index=Math.min(2,level??state.hintLevels[key]??0);state.hintLevels[key]=index;state.hintUses++;save();K.open('수사 지원 · '+(index+1)+'/3',`<p class="hint-objective">${E.objective(state)[1]}</p><p>${hintSets[key][index]}</p><div class="dialog-actions"><button data-close-dialog class="ghost">조사 계속</button>${index<2?'<button id="moreHint" class="primary">'+(index===1?'정답 확인':'더 구체적인 힌트')+'</button>':''}</div>`);if($('#moreHint'))$('#moreHint').onclick=()=>hint(index+1);}
function pause(){paused=true;save();K.open('조사를 잠시 멈춥니다.','<p>경과 시간도 함께 멈췄습니다.</p><div class="menu-stack"><button data-close-dialog class="primary">조사 계속</button><button id="exportProgress" class="ghost">진행 파일 내려받기</button><button id="loadProgress" class="ghost">진행 파일 불러오기</button><button id="resetProgress" class="text-btn">처음부터 시작</button></div><p class="fine">파일을 옮기거나 다른 브라우저에서 이어 하려면 진행 파일을 함께 보관하세요.</p>');$('#exportProgress').onclick=()=>K.export(KEY,state);$('#loadProgress').onclick=()=>$('#importFile').click();$('#resetProgress').onclick=reset;}
$('#dialog').addEventListener('close',()=>{if(!$('#dialog').open)paused=false;lastTick=performance.now()});
$('#startBtn').onclick=start;$('#newBtn').onclick=reset;$('#restartBtn').onclick=reset;$('#hintBtn').onclick=()=>hint();$('#pauseBtn').onclick=pause;$('#reviewBtn').onclick=()=>{$('#ending').classList.add('hidden');$('#game').classList.remove('hidden');update();showPanel('journal')};$('#introImport').onclick=()=>$('#importFile').click();
$('#importFile').onchange=e=>{const file=e.target.files[0];e.target.value='';if(!file)return;K.open('진행 파일을 불러올까요?','<p>현재 진행을 선택한 파일의 기록으로 바꿉니다.</p><div class="dialog-actions"><button data-close-dialog class="ghost">취소</button><button id="confirmLoad" class="primary">불러오기</button></div>');$('#confirmLoad').onclick=()=>K.import(file,KEY,raw=>{state=E.restore(raw);save();K.close();start();K.toast('진행 기록을 불러왔습니다.')})};
$$('[data-panel]').forEach(b=>b.onclick=()=>showPanel(b.dataset.panel));$$('[data-mail]').forEach(b=>b.onclick=()=>showMail(b.dataset.mail));
$('#photoGrid').onclick=e=>{const b=e.target.closest('[data-photo]');if(!b)return;const id=b.dataset.photo,p=photos[id];mark('photo'+id);K.open('IMG_1016_'+id,`<div class="detail-photo photo-${id}" role="img" aria-label="${p.description}"></div><dl class="photo-meta"><div><dt>촬영 위치</dt><dd>${p.place}</dd></div><div><dt>촬영 시각</dt><dd>10월 16일 ${p.time}</dd></div></dl><p>${p.description}</p><button data-close-dialog class="primary">확인</button>`)};
$('#routeChoices').onclick=e=>{const b=e.target.closest('[data-route]');if(!b||b.disabled)return;const id=b.dataset.route;state.photoOrder=state.photoOrder.includes(id)?state.photoOrder.filter(x=>x!==id):[...state.photoOrder,id];$('#routeError').textContent='';save();renderPhotos()};
$('#checkRoute').onclick=()=>{if(state.photoOrder.join('')!=='ABC'){$('#routeError').textContent=state.photoOrder.length<3?'사진 세 장을 모두 선택해 주세요.':'전송 순서가 맞지 않습니다. 민호의 메일을 다시 확인하세요.';return}state.routeSolved=true;save();update();K.toast('전송 목록 복원 완료 · 역 이름을 찾았습니다.')};
$('#vaultForm').onsubmit=e=>{e.preventDefault();if(E.digits($('#vaultCode').value)!=='0823'){$('#vaultError').textContent='기억과 일치하지 않습니다. 첫 여행 날짜를 월일부터 적어보세요.';$('#vaultCode').select();return}state.vaultOpen=true;save();update();K.toast('PRIVATE의 잠금이 풀렸습니다.');$('#readRecord').focus()};
$('#readRecord').onclick=()=>{if(!state.vaultOpen)return;mark('record');$('#transcript').tabIndex=-1;$('#transcript').focus()};
$('#journalList').onclick=e=>{const b=e.target.closest('[data-source]');if(!b)return;const id=b.dataset.source;showPanel(clues[id][2]);const mail=Object.keys(mails).find(k=>mails[k].clue===id);if(mail)showMail(mail)};
$('#investigatorNotes').oninput=e=>{state.notes=e.target.value;save()};['placeAnswer','timeAnswer'].forEach(id=>$('#'+id).oninput=()=>{state.report={place:$('#placeAnswer').value,code:$('#timeAnswer').value};save()});
$('#reportForm').onsubmit=e=>{e.preventDefault();const result=E.submit(state,$('#placeAnswer').value,$('#timeAnswer').value);if(!result.ok){$('#reportError').textContent=result.message;return}finish()};
setInterval(()=>{const now=performance.now(),delta=Math.min(2,(now-lastTick)/1000);lastTick=now;if(active&&!paused&&!document.hidden&&!state.finished){state.elapsed+=delta;$('#timer').textContent=timeText(state.elapsed);if(Math.floor(state.elapsed)%5===0)save()}},1000);
document.addEventListener('visibilitychange',()=>{save();lastTick=performance.now()});window.addEventListener('pagehide',save);
if(state.started){$('#startBtn').textContent=state.finished?'수사 결과 보기':'이어서 조사하기';$('#newBtn').classList.remove('hidden');$('#resumeInfo').textContent=`저장된 기록 ${state.clues.length}/8 · 조사 시간 ${timeText(state.elapsed)}`;}
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'read_case_progress',description:'수집한 단서와 현재 조사 목표를 확인합니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async()=>({content:[{type:'text',text:JSON.stringify({clues:state.clues,objective:E.objective(state)[1],finished:state.finished})}]})});document.modelContext.registerTool({name:'submit_case_solution',description:'확보한 단서를 바탕으로 실종자 위치를 제출합니다.',inputSchema:{type:'object',properties:{place:{type:'string'},code:{type:'string'}},required:['place','code'],additionalProperties:false},execute:async input=>{const result=E.submit(state,input?.place||'',input?.code||'');if(result.ok)finish();return{content:[{type:'text',text:JSON.stringify(result)}]}}})}catch{}}
