(function(){
'use strict';
const D=window.WIND_DATA,E=window.WIND_ENGINE,M=window.WIND_MUSIC;
if(!D||!E||!M)return;
const app=document.getElementById('app'),modal=document.getElementById('modal');
let state=E.initial(),active=false,storageOK=true,loadProblem=false,saveTimer=null,toastTimer=null,lastTick=Date.now(),modalKind='',pendingImport=null;
let prologueStep=0,prologueReplay=false,prologueDraft={name:'',music:true};
const ui={view:'desk',letter:1,doc:null,filter:'전체',mapEra:'current',selected:{old:null,current:null}};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={mail:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 6 9 7 9-7"/>',book:'<path d="M12 5c-3-2-6-2-9-1v15c3-1 6-1 9 1 3-2 6-2 9-1V4c-3-1-6-1-9 1Z"/><path d="M12 5v15"/>',map:'<path d="m3 6 6-3 6 3 6-3v15l-6 3-6-3-6 3Z"/><path d="M9 3v15M15 6v15"/>',note:'<path d="M6 3h14v18H6zM3 7h6M3 12h6M3 17h6M12 8h4M12 13h4"/>',news:'<path d="M5 3h16v16a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8h2V3Z"/><path d="M5 8v11M9 7h8M9 11h8M9 15h3M15 15h2"/>',settings:'<circle cx="12" cy="12" r="3"/><path d="m9 3-1 3-3 1 1 3-2 2 2 2-1 3 3 1 1 3h6l1-3 3-1-1-3 2-2-2-2 1-3-3-1-1-3Z"/>',sound:'<path d="m4 9 4 0 5-4v14l-5-4H4Z"/><path d="M17 8a6 6 0 0 1 0 8M20 5a10 10 0 0 1 0 14"/>',muted:'<path d="m4 9 4 0 5-4v14l-5-4H4Z"/><path d="m17 9 5 6m0-6-5 6"/>',arrow:'<path d="M4 12h15m-6-6 6 6-6 6"/>',back:'<path d="M20 12H5m6-6-6 6 6 6"/>',check:'<path d="m5 12 4 4L19 6"/>',pin:'<path d="m15 3 6 6-4 1-4 6-5-5 6-4Z"/><path d="m8 16-5 5"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v6l4 2"/>'};
const icon=n=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${icons[n]||icons.mail}</svg>`;
const byId=id=>D.documents.find(d=>d.id===id);
const letter=id=>D.letters[id-1];
const stage=()=>E.stage(state);
const current=()=>letter(stage());
const accessible=id=>E.availableDocuments(state).some(d=>d.id===id);
try{const raw=localStorage.getItem(E.STORAGE);if(raw)state=E.restore(JSON.parse(raw));}catch(e){loadProblem=true;if(e&&e.name==='SecurityError')storageOK=false;}
ui.letter=stage();

function toast(message){const t=document.getElementById('toast');t.textContent=message;t.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('visible'),4200);}
function save(immediate=true){
 clearTimeout(saveTimer);
 const run=()=>{state.savedAt=new Date().toISOString();try{localStorage.setItem(E.STORAGE,JSON.stringify(state));storageOK=true;}catch(e){storageOK=false;}const s=document.querySelector('[data-save-state]');if(s)s.textContent=storageOK?'이 기기에 저장됨':'진행 파일로 저장해 주세요';};
 if(immediate)run();else saveTimer=setTimeout(run,350);
}
function tick(){const now=Date.now();if(active&&state.started&&state.completed.length<5&&!document.hidden)state.playSeconds+=Math.min(20,Math.max(0,Math.floor((now-lastTick)/1000)));lastTick=now;}
function timeSpent(){return Math.max(1,Math.round(state.playSeconds/60));}
function focusMain(){const el=document.getElementById('main');if(el){el.focus({preventScroll:true});el.scrollIntoView({block:'start'});}}
function closeModal(){if(modal.open)modal.close();modalKind='';}
function dialog(title,body,kind='generic'){
 modal.className=kind==='prologue'?'prologue-dialog':'';
 modalKind=kind;modal.innerHTML=`<div class="dialog-header"><h2 id="modal-title">${title}</h2><button type="button" class="close-btn" data-action="close-modal" aria-label="창 닫기">${icon('close')}</button></div>${body}`;
 if(!modal.open)modal.showModal();
}

function intro(){
 return `<main id="main" class="intro" tabindex="-1"><section class="intro-copy"><div class="intro-brand"><div class="brand-mark">${icon('mail')}</div><span>바람마을 우체국 · 봄 우편 주간</span></div><p class="eyebrow">A LETTER FINDS ITS WAY</p><h1>바람이 쉬어 가는<br>우체국</h1><p class="lede">주소 대신 기억이 적힌 네 통의 편지.<br>마을의 오래된 기록을 펼쳐,<br>그 마음이 도착할 곳을 찾아 주세요.</p><div class="intro-meta"><span>1인용 웹탈출</span><span>난이도 상</span><span>목표 60–90분</span><span>시간제한 없음</span></div><div class="intro-actions">${state.started?`<button class="primary" data-action="continue">${state.completed.length===5?'엔딩 다시 보기':`${state.completed.length}/5 완료 · 이어하기`} ${icon('arrow')}</button><button class="secondary" data-action="new-game">새로 시작</button>`:`<button class="primary" data-action="new-game">오늘의 편지 받기 ${icon('arrow')}</button>`}<button class="plain" data-action="settings" aria-label="설정 및 진행 파일 불러오기">${icon('settings')} 설정</button></div><p class="intro-note">조사 수첩 · 단계별 힌트 · 자동 저장<br>읽다가 잠시 쉬어 가도 괜찮아요.</p>${loadProblem?'<p class="feedback">기존 저장 정보를 읽지 못했어요. 가지고 있는 진행 파일은 설정에서 불러올 수 있어요.</p>':''}</section><aside class="intro-art"><img src="assets/post-office.webp" alt="바다가 보이는 작은 우체국. 붉은 우편함 옆에서 고양이가 햇볕을 쬐고 있다."><div class="art-caption">2026년 5월 16일, 토요일<br>오늘의 우편함에는 네 개의 작은 안부가 도착했습니다.</div></aside></main>`;
}
const navs=[['desk','mail','업무 책상'],['records','book','기록 열람실'],['map','map','마을 지도'],['notebook','note','조사 수첩'],['village','news','마을 소식']];
function taskRail(){const l=current(),done=state.completed.length===5;return `<aside class="task-rail" aria-label="현재 배달 업무"><h2>오늘의 배달</h2><div class="task-sheet"><span class="number">${done?'fin.':String(l.id).padStart(2,'0')}</span><h3>${done?'모든 마음이 도착했어요':l.short}</h3><p>${done?'너울정원에는 당신의 자리가 마련되어 있어요.':l.intro}</p><div class="task-list">${D.letters.map(x=>`<div class="task-item"><span class="${state.completed.includes(x.id)?'done':''}">${state.completed.includes(x.id)?'✓':x.id+'.'}</span><span>${x.short}</span></div>`).join('')}</div><button class="primary wide" data-action="${done?'ending':'answer'}" data-id="${l.id}">${done?'저녁 식탁으로':'배달표 작성'} ${icon('arrow')}</button></div><p class="rail-label" style="color:var(--muted);margin-left:0">우체국 고양이, 우표</p><p class="quote-note">잠깐 쉬었다 보면<br>아까 못 본 것이 보이기도 해요.</p><button class="secondary wide" data-action="hint" data-id="${l.id}">🐈 ${done?'마지막 퍼즐 힌트':'고양이에게 힌트 받기'}</button><p class="sidebar-note" style="margin-top:16px">${storageOK?'진행은 이 브라우저에 자동 저장돼요. 설정에서 진행 파일도 받을 수 있어요.':'이 브라우저에서는 자동 저장이 어려워요. 설정에서 진행 파일을 내려받아 주세요.'}</p></aside>`;}
function render(){
 if(!active){app.innerHTML=intro();return;}
 const view=ui.view==='document'?'records':ui.view;
 app.innerHTML=`<header class="masthead"><button class="wordmark" data-action="nav" data-view="desk" aria-label="업무 책상으로"><span class="brand-mark">${icon('mail')}</span><span><strong>바람이 쉬어 가는 우체국</strong><small>BARAM VILLAGE POST OFFICE</small></span></button><div class="mast-meta"><span class="date">${D.date}</span><span class="save-state" data-save-state>${storageOK?'이 기기에 저장됨':'진행 파일로 저장해 주세요'}</span><div class="music-control"><button class="plain" data-action="music" aria-pressed="${state.music}" aria-label="배경음 ${state.music?'끄기':'켜기'}">${icon(state.music?'sound':'muted')}<span>${state.music?'음악 켜짐':'음악 꺼짐'}</span></button><button class="plain" data-action="settings" aria-label="설정 열기">${icon('settings')}</button></div></div></header><div class="shell"><aside class="rail" aria-label="마을 홈페이지 메뉴"><div><p class="rail-label">오늘의 임시 집배원</p><nav class="nav-list" aria-label="게임 메뉴">${navs.map(([id,ic,name])=>`<button class="nav-item ${view===id?'active':''}" data-action="nav" data-view="${id}" ${view===id?'aria-current="page"':''}>${icon(ic)}<span>${name}</span></button>`).join('')}</nav></div><div class="nav-list secondary-nav"><button class="nav-item" data-action="cards">${icon('mail')}<span>감사 엽서 ${Math.min(state.completed.length,4)}</span></button><button class="nav-item" data-action="help">${icon('book')}<span>집배원 안내서</span></button></div><div class="rail-progress"><span class="small">${esc(state.name)}의 배달 기록</span><div class="progress-track" role="progressbar" aria-label="전체 퍼즐 진행" aria-valuemin="0" aria-valuemax="5" aria-valuenow="${state.completed.length}"><div class="progress-fill" style="width:${state.completed.length*20}%"></div></div><p>${state.completed.length} / 5 &nbsp; 마음이 도착한 곳</p><span class="rail-bottom">서두르지 않아도 괜찮아요.</span></div></aside><main id="main" class="content" tabindex="-1">${ui.view!=='ending'?mobileTask():''}${mainView()}</main>${taskRail()}</div>`;
 hydrateMaps();
}
function mobileTask(){return `<div class="mobile-task"><span>${state.completed.length}/5 완료 · ${state.completed.length===5?'저녁 식탁이 기다려요':current().short}</span><div class="flex"><button class="plain" data-action="hint" data-id="${stage()}" aria-label="현재 퍼즐 힌트">힌트</button><button class="primary" data-action="${state.completed.length===5?'ending':'answer'}" data-id="${stage()}">${state.completed.length===5?'엔딩':'배달표'}</button></div></div>`;}
function heading(title,sub,number=''){return `<div class="content-head"><div><h1>${title}</h1><p>${sub}</p></div>${number?`<span class="folio" aria-hidden="true">${number}</span>`:''}</div>`;}
function mainView(){switch(ui.view){case'records':return recordsView();case'document':return documentView();case'map':return mapView();case'notebook':return notebookView();case'village':return villageView();case'cards':return cardsView();case'ending':return endingView();default:return deskView();}}
function sourceButtons(ids){return `<div class="evidence-links">${ids.map(id=>`<button class="evidence-link" data-action="document" data-id="${id}">${esc(byId(id).title)}${state.read.includes(id)?' ✓':''}</button>`).join('')}</div>`;}
function deskView(){
 const l=letter(ui.letter),done=state.completed.includes(l.id);
 return heading('오늘 도착한 편지','기억을 읽고, 그 마음이 닿을 곳을 찾아 주세요.','01')+`<div class="mail-tabs" role="group" aria-label="편지 선택">${D.letters.map(x=>`<button class="mail-tab ${x.id===ui.letter?'active':''} ${state.completed.includes(x.id)?'complete':''}" data-action="letter" data-id="${x.id}" ${x.id>stage()?'disabled':''} aria-pressed="${x.id===ui.letter}">${x.id===5?'초대장':`${String(x.id).padStart(2,'0')} 편지`}<small>${state.completed.includes(x.id)?'배달 완료':x.id>stage()?'아직 봉인됨':x.short}</small></button>`).join('')}</div><article class="letter-card"><div class="letter-topline"><div><span class="eyebrow">LETTER ${String(l.id).padStart(2,'0')}</span><p class="small muted no-margin">받는 사람 · ${esc(l.to)}</p></div><div class="postmark">바람마을<br>2026.05.16<br>봄 우편 주간</div></div><h2 class="letter-subject">${esc(l.title)}</h2><div class="letter-body">${l.body}</div><p class="letter-sign">${esc(l.sender)} 드림</p><div class="letter-bottom"><span class="stamp">${done?'배달 완료':l.tag}</span><button class="${done?'secondary':'primary'}" data-action="${done?'proof':'answer'}" data-id="${l.id}">${done?'배달 근거 다시 보기':'배달표 작성'} ${icon('arrow')}</button></div></article>${done&&l.reply?replyMarkup(l):''}${!done?`<div style="margin-top:25px"><h3>함께 살펴볼 기록</h3>${sourceButtons(l.sources)}${l.id===5?'<button class="secondary" data-action="cards" style="margin-top:20px">네 장의 감사 엽서 펼치기</button>':''}</div>`:''}${done&&l.id<5?`<div class="row-actions"><button class="primary" data-action="letter" data-id="${l.id+1}">${l.id===4?'마지막 초대장 열기':'다음 편지 열기'} ${icon('arrow')}</button><button class="plain" data-action="nav" data-view="village">마을의 달라진 소식</button></div>`:''}`;
}
function postcard(l){const c=l.reply.card;return `<article class="postcard" aria-label="${esc(c.title)}"><div class="postcard-head"><div><p class="eyebrow" style="margin-bottom:6px">THANK YOU, POST CARRIER</p><h3>${esc(c.title)}</h3></div><span class="postcard-code">${String(l.id).padStart(2,'0')}</span></div><p class="hand-note">${esc(c.rule)}</p><div class="table-wrap">${`<table><thead><tr><th scope="col">위에서 센 줄</th><th scope="col">남겨 둔 조각</th></tr></thead><tbody>${c.lines.map((s,i)=>`<tr><td>${i+1}번째</td><td><strong>${esc(s)}</strong></td></tr>`).join('')}</tbody></table>`}</div><p class="small muted no-margin">${esc(l.reply.shop)} · ${esc(l.reply.name)}</p></article>`;}
function replyMarkup(l){return `<section class="reply-card"><p class="eyebrow" style="margin-bottom:10px">도착한 답장</p><h3>${esc(l.reply.name)} 님이 보내왔어요</h3><p>${esc(l.reply.text)}</p></section>${postcard(l)}`;}
function recordsView(){const docs=E.availableDocuments(state).filter(d=>ui.filter==='전체'||d.group===ui.filter);return heading('기록 열람실',`현재 열람 가능한 기록 ${E.availableDocuments(state).length}건 · 읽은 기록 ${state.read.length}건`,'02')+`<div class="record-groups" role="group" aria-label="기록 분류">${D.groups.filter(g=>g==='전체'||E.availableDocuments(state).some(d=>d.group===g)).map(g=>`<button class="filter ${ui.filter===g?'active':''}" data-action="filter" data-group="${g}" aria-pressed="${ui.filter===g}">${g}</button>`).join('')}</div><div class="records">${docs.map(d=>`<button class="record-card" data-action="document" data-id="${d.id}"><span class="record-type">${esc(d.group)}${state.read.includes(d.id)?'<span class="read-status">읽음</span>':''}</span><h3>${esc(d.title)}</h3><p>${esc(d.summary)}</p><span class="record-foot">${esc(d.date)}${state.pins.includes(d.id)?' · 수첩 보관':''}</span></button>`).join('')}</div><p class="small muted" style="margin-top:24px">배달을 마치면 다음 편지에 필요한 기록이 열립니다. 이미 읽은 기록도 이후 배달에서 다시 쓰일 수 있어요.</p>`;}
function documentView(){const d=byId(ui.doc);if(!d||!accessible(d.id))return recordsView();return `<div class="doc-toolbar"><button class="plain" data-action="nav" data-view="records">${icon('back')} 기록 목록</button><button class="secondary" data-action="pin" data-id="${d.id}" aria-pressed="${state.pins.includes(d.id)}">${icon('pin')} ${state.pins.includes(d.id)?'수첩에 보관됨':'수첩에 보관'}</button></div><article class="document"><span class="eyebrow">${esc(d.group)}</span><h2>${esc(d.title)}</h2><p class="document-meta">${esc(d.source)} · ${esc(d.date)}</p>${d.html}</article><div class="row-actions"><button class="secondary" data-action="nav" data-view="notebook">조사 수첩에 생각 적기</button><button class="plain" data-action="letter" data-id="${stage()}">현재 편지 다시 읽기</button></div>`;}
function mapView(){if(stage()<2)return heading('마을 지도','주소 확인 업무가 시작되면 지도를 펼칠 수 있어요.','03')+`<div class="letter-card"><h2>지도 상자는 아직 우체국 안쪽에 있어요.</h2><p>첫 번째 편지의 수신인을 찾으면 다은 씨가 맡겨 둔 옛 지도와 현재 주소 대장이 도착합니다.</p><button class="primary" data-action="letter" data-id="1">첫 편지로 돌아가기</button></div>`;return heading('마을 지도','두 지도는 같은 땅을 표시합니다. 위쪽이 가리키는 방위를 확인하세요.','03')+`<div class="map-toggle" role="group" aria-label="지도 연도"><button class="${ui.mapEra==='current'?'primary':'secondary'}" data-action="map-era" data-era="current" aria-pressed="${ui.mapEra==='current'}">현재 지도 · 2026</button><button class="${ui.mapEra==='old'?'primary':'secondary'}" data-action="map-era" data-era="old" aria-pressed="${ui.mapEra==='old'}">옛 지도 · 2022</button></div><div class="document"><div class="map-slot" data-map="${ui.mapEra}"></div></div>${sourceButtons(['old-map','registry','move-note','temporary'])}`;}
function mapMarkup(era){
 const old=era==='old',cols=old?'가나다라마':'ABCDE',sel=ui.selected[era];let cells='<span></span>'+Array.from(cols,c=>`<span class="axis">${c}</span>`).join('');
 const oldMarks={'라4':'공동수도','나3':'우체국'};
 for(let r=1;r<=5;r++){cells+=`<span class="axis">${r}</span>`;for(let c=0;c<5;c++){const key=cols[c]+r,ad=old?null:D.addresses[key],mark=old?(oldMarks[key]||''):(ad.landmark==='주민 생활 구역'?'':ad.landmark);cells+=`<button type="button" class="map-cell ${mark?'landmark':''} ${sel===key?'selected':''}" data-action="map-cell" data-era="${era}" data-cell="${key}" aria-label="${key}${mark?' '+mark:''} ${old?'옛 좌표':'주소 확인'}" aria-pressed="${sel===key}"><span class="cell-coord">${key}</span>${esc(mark)}</button>`;}}
 let detail='<p>지도에서 칸을 선택해 기록을 확인하세요.</p>';
 if(sel){if(old)detail=`<p><strong>옛 좌표 ${esc(sel)}</strong>${oldMarks[sel]?` · ${oldMarks[sel]}`:''}<br>열 ${esc(sel[0])} · 행 ${esc(sel[1])}. 이 지도의 위쪽은 서쪽입니다.</p>`;else{const ad=D.addresses[sel];detail=`<p><strong>${ad.coord} · ${esc(ad.address)}</strong><br>${esc(ad.landmark)}${ad.note?`<br>${esc(ad.note)}`:''}</p>`;}}
 return `<h3>${old?'2022년 마을 구획도':'2026년 구획·도로명 지도'}</h3><p class="compass">${old?'위 ↑ 서쪽 · 오른쪽 → 북쪽':'위 ↑ 북쪽 · 오른쪽 → 동쪽'}</p><div class="coordinate-board" role="group" aria-label="${old?'옛':'현재'} 마을 5 곱하기 5 지도">${cells}</div><div class="map-legend"><span>동일한 5×5 구역 · 칸 분할 없음</span><span>색이 있는 칸: 공공시설 등</span></div><div class="map-detail" aria-live="polite">${detail}</div>`;
}
function hydrateMaps(){document.querySelectorAll('.map-slot').forEach(el=>{el.innerHTML=mapMarkup(el.dataset.map);});}
function notebookView(){const opts=E.availableDocuments(state).map(d=>`<option value="${d.id}">${esc(d.title)}</option>`).join('');return heading('조사 수첩','기록을 보관하고, 두 단서 사이에 떠오른 생각을 적어 두세요.','04')+`<label for="notes">내 메모 <span class="muted small">· 입력하면 자동 저장</span></label><textarea class="notebook-note" id="notes" maxlength="20000" placeholder="계산 순서를 적거나, 지도 방향을 비교하거나, 배달 시간을 계산해 보세요.">${esc(state.notes)}</textarea><h2 style="margin:30px 0 15px">보관한 기록 <span class="small muted">${state.pins.length}</span></h2>${state.pins.length?`<div class="pin-list">${state.pins.map(id=>`<div class="pin-row"><button data-action="document" data-id="${id}">${esc(byId(id).title)}<small>${esc(byId(id).group)} · ${esc(byId(id).date)}</small></button><button class="plain" data-action="pin" data-id="${id}" aria-label="${esc(byId(id).title)} 수첩에서 빼기">${icon('close')}</button></div>`).join('')}</div>`:'<p class="empty">기록을 열고 ‘수첩에 보관’을 누르면 여기에 모여요.</p>'}<h2 style="margin:32px 0 10px">단서 연결</h2><form id="connection-form" class="connection-form"><label>첫 번째 기록<select name="from" required><option value="">기록 선택</option>${opts}</select></label><label>함께 볼 기록<select name="to" required><option value="">기록 선택</option>${opts}</select></label><label>두 기록에서 알아낸 것<input type="text" name="note" maxlength="700" required placeholder="어떤 정보가 서로 이어지나요?"></label><button class="secondary" type="submit">연결 메모 남기기</button></form><div>${state.connections.map(c=>`<article class="connection"><div class="flex between"><small>${esc(byId(c.from).title)} ↔ ${esc(byId(c.to).title)}</small><button class="plain" data-action="remove-connection" data-id="${esc(c.id)}" aria-label="단서 연결 삭제">${icon('close')}</button></div><p>${esc(c.note)}</p><div class="flex"><button class="plain" data-action="document" data-id="${c.from}">첫 기록 열기</button><button class="plain" data-action="document" data-id="${c.to}">함께 볼 기록</button></div></article>`).join('')}</div><div class="row-actions"><button class="secondary" data-action="cards">감사 엽서 모아 보기</button></div>`;}
function villageView(){return heading('마을에 도착한 작은 변화','편지가 도착하면, 이곳에도 새로운 소식이 올라와요.','05')+`<img class="village-banner" src="assets/post-office.webp" alt="한낮의 바람마을 우체국과 바다"><article class="news-item"><time>오늘의 첫 소식 · 바람마을 우체국</time><h3>우리 마을에 하루 집배원이 왔습니다</h3><p>${esc(state.name)} 님이 네 통의 안부를 전해 주기로 했어요. 마주치면 길을 천천히 알려 주세요. 저녁에는 다 같이 얼굴을 볼 수 있겠죠.</p></article>${D.letters.filter(l=>l.id<=4&&state.completed.includes(l.id)).map(l=>`<article class="news-item"><time>${l.id}번째 편지가 도착한 뒤 · ${esc(l.reply.shop)}</time><h3>${esc(l.reply.newsTitle)}</h3><p>${esc(l.reply.news)}</p></article>`).join('')}${state.completed.length===5?'<article class="news-item"><time>오늘의 마지막 소식 · 너울정원</time><h3>한 자리가 더 차려졌습니다</h3><p>따뜻한 빵과 꽃 한 송이, 오래된 친구와 새로 만난 이웃. 오늘 저녁에는 집배원도 함께 앉았습니다.</p></article>':''}`;}
function cardsView(){const cards=D.letters.filter(l=>l.id<=4&&state.completed.includes(l.id));return heading('집배원에게 온 감사 엽서','네 사람이 남긴 짧은 메모와 작은 조각들.',String(cards.length).padStart(2,'0'))+`${cards.length?cards.map(l=>postcard(l)).join(''):'<p class="empty">첫 편지를 배달하면 감사 엽서가 도착해요.</p>'}<div class="row-actions"><button class="secondary" data-action="letter" data-id="${stage()}">현재 편지로 돌아가기</button>${state.completed.length>=4?'<button class="primary" data-action="answer" data-id="5">초대장 배달표 작성</button>':''}</div>`;}
function endingView(){if(state.completed.length<5)return deskView();return `<article class="ending"><p class="eyebrow">ALL LETTERS DELIVERED</p><h1>오늘은 당신도<br>받는 사람이에요.</h1><p class="muted">너울정원 서문 · 오후 6시 40분</p><img src="assets/post-office.webp" alt="따뜻한 햇살을 간직한 바람마을 우체국"><div class="letter-body"><p>서문을 밀자, 긴 테이블 위에 네 개의 감사 엽서가 놓여 있어요. 방금 전까지 당신의 가방에 있던 마음들이 이제 서로의 이야기가 되었습니다.</p><p>소라는 아직 따뜻한 빵을 잘라 나누고, 다은은 짧은 꽃을 작은 병에 꽂습니다. 윤슬과 하린은 단추 이야기를 하다가 웃고, 해준은 테이블 끝의 의자를 조용히 빼 줍니다.</p><p>“편지 가방은 거기에 두세요. 이제 같이 먹어요.”</p></div><div class="seat">${esc(state.name)} 님의 자리</div><div class="letter-body"><p>돌려줄 것이 없어도, 잘 설명할 말이 없어도, 오늘 저녁의 자리는 그대로입니다.</p><p>당신은 가방을 내려놓습니다.<br>바람이 잠시 쉬어 갑니다.</p></div><div class="stats"><span>다섯 퍼즐 완료</span><span>머문 시간 약 ${timeSpent()}분</span><span>열어 본 힌트 ${state.hints.reduce((a,b)=>a+b,0)}단계</span></div><div class="row-actions" style="justify-content:center"><button class="primary" data-action="nav" data-view="village">마을의 소식 다시 보기</button><button class="secondary" data-action="cards">감사 엽서 간직하기</button><button class="plain" data-action="export">진행 파일 내려받기</button></div></article>`;}

function startDialog(replay=false){
 prologueReplay=replay;prologueDraft={name:'',music:state.music};prologueDialog(0);
}
function prologueDialog(step){
 prologueStep=Math.max(0,Math.min(2,step));
 const titles=['바람이 이끈 문 앞에서','주소 대신 남아 있는 기억','오늘, 당신이 할 일'];
 const steps=['마을에 도착','우체국장의 부탁','첫 배달 준비'];
 const progress=`<ol class="prologue-steps" aria-label="이야기 안내 진행">${steps.map((title,i)=>`<li class="${i===prologueStep?'current':i<prologueStep?'visited':''}" ${i===prologueStep?'aria-current="step"':''}><span aria-hidden="true">${i+1}</span>${title}</li>`).join('')}</ol>`;
 const back=prologueStep>0?`<button type="button" class="secondary" data-action="prologue-back">${icon('back')} 앞 이야기</button>`:'';
 let body='';
 if(prologueStep===0){
  body=`<img class="prologue-image" src="assets/post-office.webp" alt="바다가 내려다보이는 작은 우체국과 붉은 우편함"><p class="prologue-setting">2026년 5월 16일 · 바람마을</p><div class="prologue-story"><p>일정을 비워 둔 여행의 오후. 바닷가 골목을 걷던 당신은 붉은 우편함 앞에서 걸음을 멈춥니다.</p><p>반쯤 열린 문틈으로 종이 넘기는 소리가 들려옵니다. 고양이 한 마리가 눈을 가늘게 뜨고, 책상 너머의 우체국장이 고개를 들어 웃습니다.</p><blockquote>“여행 오셨나 봐요. 잠깐 쉬었다 가실래요?<br>마침, 누군가의 손을 조금 빌리고 싶던 참이에요.”</blockquote></div><div class="prologue-nav"><span class="muted small">이야기 1 / 3</span><button type="button" class="primary" data-action="prologue-next">문 안으로 들어가기 ${icon('arrow')}</button></div>`;
 }else if(prologueStep===1){
  body=`<p class="prologue-setting">우체국 안 · 창가의 작은 책상</p><div class="prologue-story"><p>우체국장은 손때 묻은 노트북 옆에 편지 네 통을 내려놓습니다. 그런데 봉투에는 이름도, 주소도 적혀 있지 않습니다.</p><blockquote>“이 마을의 봄 우편 주간에는 이름 대신 <strong>함께 보낸 기억</strong>을 적어요. 고마웠지만 미처 전하지 못한 마음을, 그 사람에게 다시 보내는 거죠.”</blockquote><p>첫 봉투에는 이렇게 적혀 있습니다.<br><em>‘비 오는 날, 내 우산보다 빵 봉투를 먼저 챙겨 주었던 분께.’</em></p><blockquote>“제가 소포를 정리하는 동안, 이 편지들이 <strong>누구에게, 어디로 가야 할지</strong> 찾아 주실래요? 배달할 준비가 되면 제가 전달을 도와드릴게요.”</blockquote><p>노트북에는 마을 홈페이지가 열려 있습니다. 주민들의 글, 오래된 사진, 지도와 시간표. 흩어진 기록 사이에 편지가 찾아가는 길이 있을 것 같습니다.</p></div><div class="prologue-nav">${back}<button type="button" class="primary" data-action="prologue-next">편지를 맡아 볼게요 ${icon('arrow')}</button></div>`;
 }else{
  const guidance=`<p class="prologue-mission">네 통의 편지가<br><strong>제 주인에게 닿도록 도와주세요.</strong></p><ol class="prologue-guide"><li><span>${icon('mail')}</span><div><strong>편지에서 실마리를 찾기</strong><p>업무 책상에서 편지를 읽고, 사람·장소·시간에 관한 기억을 살펴보세요.</p></div></li><li><span>${icon('book')}</span><div><strong>마을 기록을 연결하기</strong><p>기록 열람실과 지도를 대조하세요. 중요한 단서는 조사 수첩에 보관하고 생각을 적어 둘 수 있어요.</p></div></li><li><span>${icon('check')}</span><div><strong>배달표를 작성해 전달하기</strong><p>알아낸 내용으로 배달표의 모든 칸을 채워 제출하세요. 편지가 도착하면 답장과 다음 기록이 열려요.</p></div></li></ol><p class="prologue-first"><strong>첫 번째 업무</strong><br>빵 봉투를 먼저 챙겨 주었던 사람이 누구인지 찾아주세요.</p><p class="prologue-support">시간제한은 없어요. 막히면 고양이 <strong>우표</strong>에게 단계별 힌트를 받아 보세요. 답장과 감사 엽서도 끝까지 간직해 주세요.</p>`;
  body=guidance+(prologueReplay?`<div class="prologue-nav">${back}<button type="button" class="primary" data-action="close-modal">이야기를 접어 두기 ${icon('check')}</button></div>`:`<form id="start-form"><label for="player-name">명찰에 적을 이름<input id="player-name" name="name" type="text" maxlength="30" placeholder="여행자" autocomplete="off" value="${esc(prologueDraft.name)}"></label><label class="prologue-music"><input id="prologue-music" type="checkbox" name="music" ${prologueDraft.music?'checked':''}> 잔잔한 배경음과 함께 시작</label>${state.started?'<p class="feedback">새로 시작하면 현재 배달 진행과 수첩이 새 기록으로 바뀝니다. 보관할 기록은 설정에서 진행 파일로 내려받아 주세요.</p>':''}<div class="prologue-nav">${back}<button class="primary" type="submit">${state.started?'새 명찰을 달고 처음부터':'명찰을 달고 첫 편지 열기'} ${icon('arrow')}</button></div></form>`);
 }
 dialog(titles[prologueStep],progress+body,'prologue');
 modal.scrollTop=0;
 const title=modal.querySelector('#modal-title');if(title){title.tabIndex=-1;title.focus({preventScroll:true});}
}
function answerDialog(id,feedback=''){
 const l=letter(id);if(!l||id>stage())return toast('앞선 편지를 먼저 배달해 주세요.');if(state.completed.includes(id))return proofDialog(id);
 const draft=state.drafts[id]||{};
 const fields=l.fields.map(f=>{const v=draft[f.key]??'',key=`answer-${f.key}`;let control='';if(f.type==='select')control=`<select id="${key}" name="${f.key}" required><option value="">선택해 주세요</option>${f.options.map(([val,label])=>`<option value="${esc(val)}" ${String(v)===val?'selected':''}>${esc(label)}</option>`).join('')}</select>`;else control=`<input id="${key}" name="${f.key}" type="${f.type}" value="${esc(v)}" ${f.type==='number'?`min="${f.min}" max="${f.max}" step="1"`:'maxlength="140"'} ${f.type==='time'?'step="60"':''} placeholder="${esc(f.placeholder||'')}" autocomplete="off" required>`;return `<label class="${l.fields.length%2&&f===l.fields[l.fields.length-1]?'full':''}" for="${key}">${esc(f.label)}${control}${f.hint?`<span class="field-hint">${esc(f.hint)}</span>`:''}</label>`;}).join('');
 dialog(`${id===5?'초대장':'편지 '+id} · 배달표`, `<p class="muted">${esc(l.title)}</p><form id="answer-form" data-letter="${id}"><div class="form-grid">${fields}</div>${feedback?`<p class="feedback" role="alert" tabindex="-1">${esc(feedback)}</p>`:''}<button type="submit" class="primary wide">${id===5?'약속 장소로 가기':'배달 계획 확인하고 전달하기'} ${icon('arrow')}</button></form><div class="row-actions"><button class="plain" data-action="close-modal">기록 더 살펴보기</button><button class="plain" data-action="hint" data-id="${id}">고양이에게 힌트 받기</button></div><p class="small muted" style="margin:16px 0 0">적어 둔 답은 창을 닫아도 보관됩니다.</p>`,'answer');
 if(feedback)modal.querySelector('.feedback').focus();
}
function proofDialog(id){if(!state.completed.includes(id))return;const l=letter(id),a=state.answers[id];dialog('배달 근거',`<p class="eyebrow">${esc(l.title)}</p><div class="result-proof"><p>${esc(l.proof)}</p></div><div class="table-wrap"><table><thead><tr><th scope="col">배달표</th><th scope="col">확인한 내용</th></tr></thead><tbody>${l.fields.map(f=>`<tr><td>${esc(f.label)}</td><td>${esc(f.type==='select'?(f.options.find(o=>o[0]===String(a[f.key]))||['',a[f.key]])[1]:a[f.key])}</td></tr>`).join('')}</tbody></table></div><button class="primary wide" data-action="close-modal">다시 접어 두기</button>`,'proof');}
function hintDialog(id){if(!letter(id)||id>stage())return;const l=letter(id),n=state.hints[id-1];dialog('우표가 가리키는 곳',`<p class="muted">${esc(l.title)} · 힌트 ${n}/3단계</p><div class="hint-steps" aria-hidden="true">${[1,2,3].map(i=>`<span class="hint-dot ${i<=n?'shown':''}">${i}</span>`).join('')}</div>${n===0?'<p class="hand-note">우체국 고양이 우표가 기록 옆에 자리를 잡았어요. 첫 번째 힌트는 어디를 살펴보면 좋을지 알려줍니다.</p>':l.hints.slice(0,n).map((h,i)=>`<section class="hint-box"><h3>${i+1}단계 · ${['볼 곳','연결할 정보','풀이와 정답'][i]}</h3><p>${esc(h)}</p></section>`).join('')}${n<3?`<button class="${n===2?'secondary':'primary'} wide" data-action="reveal-hint" data-id="${id}">${n+1}단계 · ${['볼 곳 알려줘','연결할 정보 보기','풀이와 정답 보기'][n]}</button>`:''}<div class="row-actions"><button class="plain" data-action="close-modal">혼자 더 생각해 볼게</button>${!state.completed.includes(id)?`<button class="plain" data-action="answer" data-id="${id}">배달표로</button>`:''}</div>`,'hint');}
function settingsDialog(){dialog('잠시 쉬어 가는 시간',`<p class="muted">음악과 진행 기록을 여기에서 관리해요.</p><div class="settings-row"><span>배경음</span><button class="secondary" data-action="music" aria-pressed="${state.music}">${state.music?'켜짐 · 끄기':'꺼짐 · 켜기'}</button></div><div class="settings-row"><label for="volume">음량 <span id="volume-value">${Math.round(state.volume*100)}%</span></label><input id="volume" type="range" min="0" max="100" value="${Math.round(state.volume*100)}" aria-label="배경음 음량"></div><hr class="divider"><h3>진행 기록</h3><p class="small">${state.started?`${esc(state.name)} · ${state.completed.length}/5 완료 · 약 ${timeSpent()}분`:'아직 배달을 시작하지 않았어요.'}<br>${storageOK?'현재 브라우저에 자동 저장합니다.':'브라우저 자동 저장을 사용할 수 없어요. 진행 파일을 내려받아 보관해 주세요.'}</p><p class="small muted">다른 폴더나 기기로 옮길 때는 진행 파일을 함께 가져가세요.</p><div class="row-actions"><button class="secondary" data-action="export">진행 파일 내려받기</button></div><label for="import-file" style="margin-top:20px">진행 파일 불러오기<input type="file" id="import-file" accept=".json,application/json" class="file-input"></label><p class="field-hint">불러올 내용을 확인한 뒤 현재 기록에 반영합니다.</p><hr class="divider"><div class="row-actions"><button class="plain" data-action="help">집배원 안내서</button>${active?'<button class="plain" data-action="title-screen">시작 화면으로</button>':''}${state.started?'<button class="plain" data-action="new-game">새로운 하루 시작</button>':''}</div><p class="version-note" style="margin-top:20px">바람이 쉬어 가는 우체국 · 1.1 · Escape Archive</p>`,'settings');}
function helpDialog(){dialog('집배원 안내서',`<button class="secondary wide" data-action="prologue-replay" style="margin:8px 0 24px">${icon('book')} 우체국장의 이야기 다시 읽기</button><ol><li><strong>업무 책상</strong>에서 현재 편지를 읽어요.</li><li><strong>기록 열람실</strong>의 자료를 비교해 수신인·주소·시간을 추리해요. 모든 정보는 게임 안에 있어요.</li><li>중요한 기록은 <strong>수첩에 보관</strong>하고, 조사 수첩에서 기록끼리 연결하거나 메모를 적어요.</li><li><strong>배달표</strong>의 모든 칸을 채워 제출해요. 정답이면 답장과 새 기록이 열려요.</li><li>마지막 초대장은 네 장의 <strong>감사 엽서</strong>와 이전에 알아낸 정보를 함께 써서 풀어요.</li></ol><p>시간제한이나 오답으로 인한 종료는 없어요. 버스와 물때의 시각은 퍼즐 속 조건이며, 실제로 기다릴 필요는 없습니다.</p><p>힌트는 ‘볼 곳 → 연결할 정보 → 풀이와 정답’ 세 단계예요. 마지막 단계에는 정답이 공개됩니다.</p><p>음악은 시작 또는 켜기 버튼을 누른 뒤 재생됩니다. 설정에서 음량을 조절하거나 진행 파일을 받을 수 있어요.</p><button class="primary wide" data-action="close-modal">알겠어요</button>`,'help');}
async function musicUpdate(on){state.music=on;save();const ok=await M.setEnabled(on,state.volume);if(on&&!ok){state.music=false;save();toast('이 브라우저에서 배경음을 시작하지 못했어요. 게임은 계속할 수 있어요.');}const kind=modalKind;if(active)render();else render();if(kind==='settings')settingsDialog();}
function openDoc(id){if(!accessible(id))return toast('이 기록은 다음 배달에서 열려요.');closeModal();ui.doc=id;ui.view='document';if(!state.read.includes(id))state.read.push(id);save();render();focusMain();}
function navigate(view){if(!['desk','records','map','notebook','village','cards','ending'].includes(view))return;closeModal();ui.view=view;if(view==='desk')ui.letter=stage();render();focusMain();}
function exportSave(){tick();save();const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='wind-post-office-progress.json';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);toast('진행 파일을 내려받았어요.');}
async function importFile(file){
 if(!file)return;if(file.size>256000)return toast('진행 파일은 256KB 이하의 JSON 파일이어야 해요.');
 try{pendingImport=E.restore(JSON.parse(await file.text()));dialog('이 기록으로 이어갈까요?',`<p><strong>${esc(pendingImport.name)}</strong> · ${pendingImport.completed.length}/5 완료</p><p class="small muted">현재 기록을 불러온 기록으로 바꿉니다. 조사 수첩과 힌트 기록도 함께 반영됩니다.</p><div class="row-actions"><button class="primary" data-action="confirm-import">이 기록 불러오기</button><button class="secondary" data-action="cancel-import">취소</button></div>`,'import');}
 catch(e){pendingImport=null;toast('이 게임의 올바른 진행 파일을 읽을 수 없어요. 현재 기록은 그대로예요.');}
}
function handleDelivery(id,answer){
 if(!active||!state.started)return {ok:false,reason:'not_started'};
 const result=E.submit(state,id,answer);state=result.state;save();
 if(!result.ok){answerDialog(id,'배달표가 아직 기록과 맞지 않아요. 여러 기록의 시점과 조건을 함께 확인해 주세요.');return {ok:false,reason:result.reason};}
 closeModal();ui.letter=id;ui.view=id===5?'ending':'desk';render();focusMain();toast(id===5?'당신에게도 편지가 도착했습니다.':'편지가 도착했어요. 답장과 감사 엽서를 확인해 주세요.');return {ok:true,completed:state.completed.length};
}
document.addEventListener('click',async event=>{
 const target=event.target.closest('[data-action]');if(!target||target.disabled)return;
 const a=target.dataset.action,id=Number(target.dataset.id);
 switch(a){
 case'new-game':startDialog();break;
 case'prologue-replay':startDialog(true);break;
 case'prologue-next':if(modalKind==='prologue'&&prologueStep<2)prologueDialog(prologueStep+1);break;
 case'prologue-back':if(modalKind==='prologue'&&prologueStep>0)prologueDialog(prologueStep-1);break;
 case'continue':active=true;lastTick=Date.now();ui.view=state.completed.length===5?'ending':'desk';ui.letter=stage();render();focusMain();if(state.music)await musicUpdate(true);break;
 case'nav':navigate(target.dataset.view);break;
 case'letter':if(id>=1&&id<=stage()){closeModal();ui.letter=id;ui.view='desk';render();focusMain();}break;
 case'answer':answerDialog(id);break;
 case'proof':proofDialog(id);break;
 case'close-modal':closeModal();break;
 case'document':openDoc(target.dataset.id);break;
 case'filter':ui.filter=target.dataset.group;render();break;
 case'pin':{const key=target.dataset.id;if(!accessible(key))break;const had=state.pins.includes(key);state.pins=had?state.pins.filter(x=>x!==key):[...state.pins,key];save();const y=window.scrollY;render();window.scrollTo(0,y);toast(had?'수첩에서 기록을 꺼냈어요.':'조사 수첩에 기록을 보관했어요.');break;}
 case'map-era':ui.mapEra=target.dataset.era==='old'?'old':'current';render();break;
 case'map-cell':{const era=target.dataset.era,cell=target.dataset.cell;if(stage()<2||!['old','current'].includes(era))break;ui.selected[era]=cell;const slot=target.closest('.map-slot');slot.innerHTML=mapMarkup(era);const b=slot.querySelector(`[data-cell="${cell}"]`);if(b)b.focus({preventScroll:true});break;}
 case'cards':navigate('cards');break;
 case'hint':hintDialog(id);break;
 case'reveal-hint':if(id>=1&&id<=stage()){state.hints[id-1]=Math.min(3,state.hints[id-1]+1);save();hintDialog(id);}break;
 case'settings':settingsDialog();break;
 case'help':helpDialog();break;
 case'music':await musicUpdate(!state.music);break;
 case'export':exportSave();break;
 case'ending':if(state.completed.length===5)navigate('ending');break;
 case'remove-connection':state.connections=state.connections.filter(c=>c.id!==target.dataset.id);save();render();break;
 case'confirm-import':if(pendingImport){state=pendingImport;pendingImport=null;active=state.started;ui.letter=stage();ui.view=state.completed.length===5?'ending':'desk';ui.filter='전체';ui.selected={old:null,current:null};lastTick=Date.now();loadProblem=false;closeModal();save();render();focusMain();if(active&&state.music)await musicUpdate(true);else await M.setEnabled(false);toast('진행 기록을 불러왔어요.');}break;
 case'cancel-import':pendingImport=null;settingsDialog();break;
 case'title-screen':tick();save();active=false;closeModal();await M.setEnabled(false);render();focusMain();break;
 }
});
document.addEventListener('submit',async event=>{
 if(!['start-form','answer-form','connection-form'].includes(event.target.id))return;event.preventDefault();const form=event.target,values=Object.fromEntries(new FormData(form).entries());
 if(form.id==='start-form'){
  if(modalKind!=='prologue'||prologueStep!==2||prologueReplay)return;
  const vol=state.volume;state=E.initial();state.volume=vol;state.started=true;state.name=String(values.name||'여행자').trim().slice(0,30)||'여행자';state.music=values.music==='on';active=true;lastTick=Date.now();loadProblem=false;ui.view='desk';ui.letter=1;ui.filter='전체';ui.selected={old:null,current:null};closeModal();save();render();focusMain();if(state.music)await musicUpdate(true);else await M.setEnabled(false);return;
 }
 if(form.id==='answer-form'){handleDelivery(Number(form.dataset.letter),values);return;}
 if(form.id==='connection-form'){
  if(!accessible(values.from)||!accessible(values.to)||values.from===values.to)return toast('서로 다른 두 기록을 골라 주세요.');
  const note=String(values.note||'').trim().slice(0,700);if(!note)return toast('두 기록에서 알아낸 것을 적어 주세요.');if(state.connections.length>=100)return toast('단서 연결은 100개까지 보관할 수 있어요.');
  state.connections.push({id:`link-${Date.now()}-${state.connections.length}`,from:values.from,to:values.to,note});save();render();toast('두 기록을 연결했어요.');
 }
});
document.addEventListener('input',event=>{
 const t=event.target;
 if(modalKind==='prologue'&&!prologueReplay){if(t.id==='player-name')prologueDraft.name=t.value.slice(0,30);if(t.id==='prologue-music')prologueDraft.music=t.checked;}
 if(t.id==='notes'){state.notes=t.value.slice(0,20000);save(false);}
 if(t.id==='volume'){state.volume=Number(t.value)/100;M.setVolume(state.volume);const v=document.getElementById('volume-value');if(v)v.textContent=`${t.value}%`;save(false);}
 const form=t.closest('#answer-form');if(form){const id=Number(form.dataset.letter);state.drafts[id]=E.cleanAnswer(id,Object.fromEntries(new FormData(form).entries()));save(false);}
});
document.addEventListener('change',event=>{if(event.target.id==='import-file')importFile(event.target.files[0]);});
modal.addEventListener('cancel',()=>{modalKind='';pendingImport=null;});
modal.addEventListener('click',event=>{if(event.target===modal){const r=modal.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)closeModal();}});
document.addEventListener('visibilitychange',()=>{lastTick=Date.now();if(state.started)save();});
window.addEventListener('pagehide',()=>{tick();if(state.started)save();});
setInterval(()=>{tick();if(active)save();},15000);

// Optional browser-native tools use the same guarded actions as the visible game.
function registerTools(){const context=document.modelContext;if(!context||typeof context.registerTool!=='function')return;const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});const tools=[
 {name:'read_post_office_progress',title:'Read delivery progress',description:'Read current game progress and available document titles without revealing solutions.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(!input||Object.keys(input).length)throw new Error('Expected empty object');return {started:state.started,completed:[...state.completed],currentLetter:stage(),documents:E.availableDocuments(state).map(d=>({id:d.id,title:d.title,read:state.read.includes(d.id)}))};}},
 {name:'open_post_office_document',title:'Open a village record',description:'Navigate to an unlocked record in the active game and mark it read.',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!active||!input||typeof input.id!=='string'||Object.keys(input).some(k=>k!=='id')||!accessible(input.id))throw new Error('Record unavailable');openDoc(input.id);return {opened:input.id};}},
 {name:'submit_post_office_delivery',title:'Submit the completed delivery form',description:'Check a filled delivery form for the current unlocked letter using the same rules as the visible form; a correct answer completes that puzzle.',inputSchema:{type:'object',properties:{letter:{type:'integer',minimum:1,maximum:5},answer:{type:'object',additionalProperties:{type:'string'}}},required:['letter','answer'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||!Number.isInteger(input.letter)||input.letter<1||input.letter>stage()||!input.answer||typeof input.answer!=='object'||Array.isArray(input.answer)||Object.keys(input).some(k=>!['letter','answer'].includes(k)))throw new Error('Invalid delivery input');return handleDelivery(input.letter,input.answer);}}
 ];for(const tool of tools){try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch(e){/* Optional API unavailable. */}}}
window.WindPostReady=true;render();registerTools();
})();
